backend:
  name: git-gateway
  branch: main

# Editorial workflow for content approval
publish_mode: editorial_workflow

local_backend:
  url: http://localhost:8082

media_folder: "site/static/img"
public_folder: "/img"

# Site URL for proper preview - UPDATE WITH YOUR ACTUAL NETLIFY URL
site_url: https://karma-project-web.netlify.app
display_url: https://karma-project-web.netlify.app

collections:
  - name: "products"
    label: "Товари"
    folder: "site/content/catalog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Назва товару", name: "title", widget: "string"}
      - {label: "Опис", name: "description", widget: "text"}
      - {label: "Дата створення", name: "date", widget: "datetime"}
      - {label: "Категорія", name: "category", widget: "select", options: ["politni-steky", "videoperedavachi-vtx", "esc"]}
      - {label: "ID товару", name: "product_id", widget: "string"}
      - {label: "Зображення", name: "image", widget: "image"}
      - {label: "Ціна", name: "price", widget: "number"}
      - {label: "Валюта", name: "currency", widget: "select", options: ["грн", "USD", "EUR"], default: "грн"}
      - {label: "В наявності", name: "in_stock", widget: "boolean", default: true}
      - label: "Характеристики"
        name: "specs"
        widget: "list"
        fields:
          - {label: "Назва", name: "label", widget: "string"}
          - {label: "Значення", name: "value", widget: "string"}
      - label: "SEO налаштування"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - {label: "SEO заголовок", name: "seo_title", widget: "string", required: false, hint: "Заголовок для пошукових систем (50-60 символів)"}
          - {label: "SEO опис", name: "seo_description", widget: "text", required: false, hint: "Опис для пошукових систем (150-160 символів)"}
          - {label: "SEO зображення", name: "seo_image", widget: "image", required: false, hint: "Зображення для соціальних мереж (1200x630px)"}
          - {label: "Alt текст для SEO зображення", name: "seo_image_alt", widget: "string", required: false}
          - {label: "Приховати від індексації", name: "noindex", widget: "boolean", default: false}
      - {label: "Детальний опис", name: "body", widget: "markdown"}
      - {label: "Чернетка", name: "draft", widget: "boolean", default: false}
  - name: "knowledge-base"
    label: "База знань"
    folder: "site/content/guides"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Назва", name: "title", widget: "string"}
      - {label: "Опис", name: "description", widget: "text"}
      - {label: "Дата публікації", name: "date", widget: "datetime"}
      - {label: "Категорія", name: "category", widget: "select", options: ["БПЛА", "Політні стеки", "Відеопередавачі", "ESC"]}
      - label: "Теги"
        name: "tags"
        widget: "list"
        required: false
        field: {label: "Тег", name: "tag", widget: "string"}
      - {label: "Зображення", name: "image", widget: "image", required: false}
      - label: "SEO налаштування"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - {label: "SEO заголовок", name: "seo_title", widget: "string", required: false, hint: "Заголовок для пошукових систем (50-60 символів)"}
          - {label: "SEO опис", name: "seo_description", widget: "text", required: false, hint: "Опис для пошукових систем (150-160 символів)"}
          - {label: "SEO зображення", name: "seo_image", widget: "image", required: false, hint: "Зображення для соціальних мереж (1200x630px)"}
          - {label: "Alt текст для SEO зображення", name: "seo_image_alt", widget: "string", required: false}
          - {label: "Приховати від індексації", name: "noindex", widget: "boolean", default: false}
      - {label: "Чернетка", name: "draft", widget: "boolean", default: false}
      - {label: "Контент", name: "body", widget: "markdown"}
  - name: "post"
    label: "Post"
    folder: "site/content/post"
    path: "{{slug}}/index"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
